name: 'Check as aqua custom registry'

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
    paths:
      - 'registry.yaml'
      - 'aqua/**.yaml'
  workflow_dispatch:

jobs:
  validate-registry:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v5'
      - uses: aquaproj/aqua-installer@9ebf656952a20c45a5d66606f083ff34f58b8ce0 # v4.0.0
        with:
          aqua_version: v2.43.1
